### PR TITLE
Refactor screen instantiation and auto-formatting

### PR DESCRIPTION
**Pull request by jmtaber129**
Refactored the instantiation of screens to occur within the screen calling setScreen(), rather than having FilePlayMain instantiate the screen.  Also changed FilePlayMain to extend from Game (instead of ApplicationAdapter).  Also ran auto-formatter/import optimizer on screen classes and FilePlayMain.

### CODE REVIEW

**Review by cvasqu09 — COMMENTED** [review]
Everything looks good however I am getting the handshake error when transitioning to the play screen because of the certificate. Do you have the certificate on your machine? If so what did you do to add it to the keystore?

**Comment by jmtaber129** [comment]
I haven't added the cert to my machine yet, so I've been testing the Play screen on the emulator, which seems to have the cert (although this quite inefficient).  I need to find the Windows command for adding certs to the keystore.  Once the trivia question objects are organized in such a way that the web dependency can be injected, I'd like to create a stub and/or fake of the service so we can run the desktop version without needing the cert or an internet connection.

**Comment by zliving** [comment]
The way to add it is the same as it is on mac. https://github.com/zliving/File-Play/issues/29

**Comment by jmtaber129** [comment]
I just added the cert to both x64 and x86 jre keystores, but the desktop version still throws a validator exception.  There seems to be another cacerts keystore under the android studio directory, but it seems to have a different password.

**Comment by cvasqu09** [comment]
I'm about to test it on my machine. Worst case scenario is to have the strings that are returned from the database locally.

**Comment by cvasqu09** [comment]
@jmtaber129  I got it working on my machine. Be sure that you import the certificate into the right jdk that Android Studio uses. I have an updated Java JDK and JRE however I think Android Studio is still using one of the older versions. When the error is thrown the first line tells you which one you should be importing the certificate to:
[https://docs.google.com/document/d/1iYoV8nViYhTzzqurGwvEdZdWI0Nm0xPUXqX6MgsHCUs/edit](url)

**Comment by cvasqu09** [comment]
I don't know why Github doesn't like the link. I posted a picture in the CS3365 folder in the document "Android Studio solutions"

**Comment by jmtaber129** [comment]
The JRE being used was different from the one shown in your screenshot.  I edited the config for DesktopLauncher to use the jre with the updated keystore, and it works now.

**Comment by cvasqu09** [comment]
Okay good. Did you need to make any other changes? I'm about to pull the request in.

**Comment by jmtaber129** [comment]
No more changes for now.  Go ahead.

**Review by cvasqu09 — APPROVED** [review]
Everything looks good.

**Pull request merged**
